#!/bin/sh

fileDate=`date +%F_%H-%M-%S`
fileName=".png"
FILENAME=$fileDate$fileName
FILELOCATION="$HOME/Pictures/screenshots/"

case "$1" in
    "") maim -s $FILELOCATION$FILENAME || exit;;
    "full") maim $FILELOCATION$FILENAME || exit;;
esac

xclip -selection clipboard -t image/png -i $FILELOCATION$FILENAME
